language: node_js
node_js:
- '0.10'
install: npm install
env:
  global:
  - secure: OulwNX1O8gK0ClTjTu1kQa8p2YVp2ho03l5WUBqkCL5eKHxF3yzvUMBdqLJaLsb1esyovx56VjTYA0sZYJGQGUfVoCV03DivVCzNXSKDPdmGsB8ex4EfM4gKecrboO5u8z0kXK2C6LiaDPUMcZxTQFJwpaL9tWUTaO4i79BNrYA=
  - secure: A9qkOqifUSit6GtAKbeBFphf0hsejVnHh5rEx28tvKDmREWA1201M4V4EfWn60udrZIjYQ2ylqt0m3xW3A3Z1q7v9WEx5JjYl9zBGljF6yrKQ4if7eD6etKUApvOF88mwc4j6cGtYGYPHQfLZ6CV8mCLXu/Omf0GPXNqhs8pPJE=
addons:
  sauce_connect: true
